package com.jmgits.sample.audit.view;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.CredentialsContainer;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;

@Getter
@Setter
@EqualsAndHashCode(of = "username")
public class Principal implements UserDetails, CredentialsContainer {

    private String username;

    private String password;

    private Boolean passwordAutogenerated;

    private Collection<GrantedAuthority> authorities;

    private boolean accountNonExpired;

    private boolean accountNonLocked;

    private boolean credentialsNonExpired;

    private boolean enabled;

    private TokenData tokenData;

    @Override
    public void eraseCredentials() {
        this.password = null;

    }

}
